services:
  db:
    image: postgres:alpine
    container_name: jobby-postgres
    volumes:
      - "$DATA_DIR/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: jobby
      POSTGRES_USER: jobby
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: unless-stopped
    secrets:
      - db_password
    healthcheck:
      test: ["CMD", "pg_isready", "--username=$UID"]
      interval: 5s
    user: "${UID:-1000}:${GID:-1000}"

  web:
    build:
      context: .
      args:
        # Pass the UID and GID to the Dockerfile, so we can create a user with
        # the same UID and GID as the host. This is necessary for permissions
        # on the media uploads directory.
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: jobby-app
    volumes:
      - "$CONFIG_DIR/.secrets:/jobby/.secrets:ro"
      - "$DATA_DIR/media:/jobby/media"
    env_file:
      - "$CONFIG_DIR/.env"
    ports:
      - 8787:8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: [ "/jobby/docker-entrypoint.sh" ]
    command: [ "/jobby/jobby-server/apachectl", "start", "-DFOREGROUND" ]
    user: "${UID:-1000}:${GID:-1000}"

secrets:
  db_password:
    file: "$CONFIG_DIR/.secrets/.passwd"
