site_name: Hilfe - jobby
nav:
  - Index: index.md
  - Installation: install.md
  - Die Suche: suche.md
  - Detailansicht: detail.md
  - Die Merkliste: merkliste.md
  - Papierkorb: papierkorb.md
  - Support: support.md
  - Deinstallation: deinstall.md
plugins:
  - search
  - print-site:
      add_table_of_contents: false