# Generated by Django 5.0.6 on 2024-05-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stellenangebot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titel", models.CharField(max_length=256, verbose_name="Titel")),
                ("refnr", models.CharField(max_length=256, verbose_name="Referenz-Nummer")),
                ("beruf", models.CharField(blank=True, max_length=256, null=True, verbose_name="Beruf")),
                ("arbeitgeber", models.CharField(blank=True, max_length=256, null=True, verbose_name="Arbeitgeber")),
                ("eintrittsdatum", models.DateField(blank=True, null=True, verbose_name="Eintrittsdatum")),
                ("veroeffentlicht", models.DateField(blank=True, null=True, verbose_name="Veröffentlicht am")),
                (
                    "bewerbungsstatus",
                    models.CharField(
                        choices=[
                            ("nicht beworben", "Nicht Beworben"),
                            ("geplant", "Geplant"),
                            ("beworben", "Beworben"),
                            ("abgelehnt", "Abgelehnt"),
                            ("angenommen", "Angenommen"),
                            ("---", "Nicht Geplant"),
                        ],
                        default="---",
                        max_length=256,
                        verbose_name="Bewerbungsstatus",
                    ),
                ),
                ("notizen", models.TextField(verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Stellenangebot",
                "verbose_name_plural": "Stellenangebote",
            },
        ),
        migrations.AlterModelOptions(
            name="suchemodel",
            options={"verbose_name": "Such-Parameter", "verbose_name_plural": "Such-Parameter"},
        ),
        migrations.CreateModel(
            name="StellenangebotKontakt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kontakt_typ",
                    models.CharField(
                        choices=[("E-Mail", "Email"), ("Telefon", "Telefon"), ("Anschrift", "Anschrift")],
                        max_length=256,
                        verbose_name="Art",
                    ),
                ),
                ("kontakt_daten", models.CharField(max_length=256, verbose_name="Daten")),
                (
                    "angebot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="kontakte", to="jobby.stellenangebot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StellenangebotURLs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField()),
                (
                    "angebot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="urls", to="jobby.stellenangebot"
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
            },
        ),
    ]
