# Generated by Django 5.0.6 on 2024-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0002_stellenangebot_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="stellenangebot",
            name="arbeitsort",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="stellenangebot",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
