# Generated by Django 5.0.6 on 2024-06-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0004_watchlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"verbose_name": "Merkliste", "verbose_name_plural": "Merklisten"},
        ),
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"verbose_name": "Gemerktes Stellenangebot", "verbose_name_plural": "Gemerkte Stellenangebote"},
        ),
    ]
