# Generated by Django 5.0.6 on 2024-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0006_alter_stellenangebot_notizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suchemodel",
            name="behinderung",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="corona",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
