# Generated by Django 5.0.6 on 2024-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0007_alter_suchemodel_behinderung_alter_suchemodel_corona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stellenangebot",
            name="refnr",
            field=models.CharField(max_length=256, unique=True, verbose_name="Referenz-Nummer"),
        ),
    ]
