# Generated by Django 5.0.6 on 2024-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0008_alter_stellenangebot_refnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stellenangebot",
            name="refnr",
            field=models.CharField(
                error_messages={"unique": "Stellenangebot mit dieser Referenz-Nummer existiert bereits"},
                max_length=256,
                unique=True,
                verbose_name="Referenz-Nummer",
            ),
        ),
    ]
