# Generated by Django 5.0.6 on 2024-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0010_make_bewerbungsstatus_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stellenangebot",
            name="bewerbungsstatus",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "---"),
                    ("nicht beworben", "Nicht Beworben"),
                    ("geplant", "Geplant"),
                    ("beworben", "Beworben"),
                    ("abgelehnt", "Abgelehnt"),
                    ("angenommen", "Angenommen"),
                    ("nicht geplant", "Nicht Geplant"),
                ],
                default="nicht geplant",
                max_length=256,
                null=True,
                verbose_name="Bewerbungsstatus",
            ),
        ),
    ]
