# Generated by Django 5.0.6 on 2024-06-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0011_alter_stellenangebot_bewerbungsstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suchemodel",
            old_name="umfeld",
            new_name="umkreis",
        ),
    ]
