# Generated by Django 5.0.6 on 2024-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0012_rename_umfeld_suchemodel_umkreis"),
    ]

    operations = [
        migrations.AddField(
            model_name="stellenangebot",
            name="externe_url",
            field=models.URLField(blank=True, null=True, verbose_name="Externe URL"),
        ),
    ]
