# Generated by Django 5.0.6 on 2024-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0014_alter_stellenangebot_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="stellenangebot",
            name="beschreibung",
            field=models.TextField(blank=True, verbose_name="Beschreibung"),
        ),
    ]
