# Generated by Django 5.0.6 on 2024-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0015_stellenangebot_beschreibung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suchemodel",
            name="page",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="size",
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="umkreis",
            field=models.PositiveSmallIntegerField(blank=True, default=25, null=True),
        ),
    ]
