# Generated by Django 5.0.6 on 2024-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0016_suche_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stellenangebot",
            name="arbeitgeber",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="Arbeitgeber"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stellenangebot",
            name="arbeitsort",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stellenangebot",
            name="beruf",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="Beruf"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stellenangebot",
            name="notizen",
            field=models.TextField(blank=True, default="", verbose_name="Notizen"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="arbeitgeber",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="arbeitszeit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vz", "Vollzeit"),
                    ("tz", "Teilzeit"),
                    ("snw", "Schicht/Nachtarbeit/Wochenende"),
                    ("ho", "Heim-/Telearbeit"),
                    ("mj", "Minijob"),
                ],
                default="",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suchemodel",
            name="berufsfeld",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
    ]
