# Generated by Django 5.0.6 on 2024-06-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0017_remove_textfield_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="StellenangebotFiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=256, verbose_name="Beschreibung")),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Datei")),
                (
                    "angebot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="jobby.stellenangebot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewerbungsunterlagen",
                "verbose_name_plural": "Bewerbungsunterlagen",
            },
        ),
    ]
