# Generated by Django 5.0.6 on 2024-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0018_stellenangebotfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suchemodel",
            name="size",
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
