# Generated by Django 5.0.6 on 2024-06-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0020_fts_extension"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stellenangebotkontakt",
            options={"verbose_name": "Kontaktdaten", "verbose_name_plural": "Kontaktdaten"},
        ),
    ]
