# Generated by Django 5.0.6 on 2024-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0021_alter_stellenangebotkontakt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stellenangebot",
            name="api",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
