# Generated by Django 5.0.6 on 2024-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0023_alter_stellenangeboturls_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="name",
            field=models.CharField(default="default", max_length=256, unique=True),
        ),
    ]
