# Generated by Django 5.0.6 on 2024-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0024_alter_watchlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stellenangebot",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
